steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t',
            'us-central1-docker.pkg.dev/mx-management-site/morningexapi/morningexapiproduction',
            'DOCKER_BUILDKIT=1',
            '.' ]
    env: